export default [
    {
        id: 1,
        name: "ACEtoberfest", 
        image: "ace.png", 
        link: "https://fb.me/e/blSXy29Xp",
        guys: 140,
        girls: 85,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "ACE",
        contact: "email@gmail.com"
    },
    {
        id: 2,
        name: "Phi Delt Las Vegas", 
        image: "comingSoon.jpg", 
        link: "https://www.eventbrite.com/e/phi-delt-las-vegas-tickets-731622431387?utm_experiment=test_share_listing&aff=ebdsshios",
        guys: 225,
        girls: 70,
        included: "shirt, koozie, food, Friday transportation",
        tshirt: "shirtSoon.jpg",
        org: "Phi Delt",
        contact: "email@gmail.com"
    },
    {
        id: 3,
        name: "The Masters", ***
        image: "comingSoon.jpg", 
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 1,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "Gents/Suits",
        contact: "email@gmail.com"
    },
    {
        id: 4,
        name: "Sigma Chi Yacht Club", 
        image: "comingSoon.jpg", 
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "Sigma Chi",
        contact: "email@gmail.com"
    },
    {
        id: 5,
        name: "Pike Saloon", 
        image: "comingSoon.jpg", 
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "Pike",
        contact: "email@gmail.com"
    },
    {
        id: 6,
        name: "Delts Angels", 
        image: "comingSoon.jpg", 
        link: "https://my.cheddarup.com/c/delts-angels?cart=06ce22e7-7c54-48f6-a204-44d95640d20f%21%2169891782",
        guys: 185,
        girls: 80,
        included: "shirt, fanny pack, bandana, tattoos, chapstick",
        tshirt: "shirtSoon.jpg",
        org: "Delt",
        contact: "email@gmail.com"
    },
    {
        id: 7,
        name: "Kappa Sigma Margaritaville", 
        image: "comingSoon.jpg", 
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "Kappa Sigma",
        contact: "email@gmail.com"
    },
    {
        id: 8,
        name: "Beta Born in the USA", 
        image: "comingSoon.jpg", 
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "Beta",
        contact: "email@gmail.com"
    },
    {
        id: 9,
        name: "Willystock",
        image: "comingSoon.jpg",
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "Centuries",
        contact: "email@gmail.com"
    },
    {
        id: 10,
        name: "Chili Olympics",
        image: "comingSoon.jpg",
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "AMA",
        contact: "email@gmail.com"
    },
    {
        id: 11,
        name: "Shipwrecked",
        image: "comingSoon.jpg",
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "Sig Ep",
        contact: "email@gmail.com"
    },
    {
        id: 12,
        name: "Phis in Cairo",
        image: "comingSoon.jpg",
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "Alpha Sig/Delta Sig/Phi Psi",
        contact: "email@gmail.com"
    },
    {
        id: 13,
        name: "The Donks",
        image: "comingSoon.jpg",
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "Ol' Ags",
        contact: "email@gmail.com"
    },
    {
        id: 14,
        name: "Taulapalooza",
        image: "comingSoon.jpg",
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "ATO/TKE",
        contact: "email@gmail.com"
    },
    {
        id: 15,
        name: "Space Rodeo",
        image: "comingSoon.jpg",
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "SAE",
        contact: "email@gmail.com"
    },
    {
        id: 16,
        name: "Fiji 500",
        image: "comingSoon.jpg",
        link: "fijichilifest.com",
        guys: 145,
        girls: 85,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "Fiji",
        contact: "email@gmail.com"
    }
]