export default [
    {
        id: 1,
        name: "ACEtoberfest", 
        image: "ace.png", 
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        contact: "ACE",
        email: "email@gmail.com"
    },
    {
        id: 2,
        name: "Phi Delt Las Vegas", 
        image: "comingSoon.jpg", 
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        contact: "Phi Delt",
        email: "email@gmail.com"
    },
    {
        id: 3,
        name: "The Masters", 
        image: "comingSoon.jpg", 
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 1,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        contact: "Gents/Suits",
        email: "email@gmail.com"
    },
    {
        id: 4,
        name: "Sigma Chi Yacht Club", 
        image: "comingSoon.jpg", 
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        contact: "Sigma Chi",
        email: "email@gmail.com"
    },
    {
        id: 5,
        name: "Pike Saloon", 
        image: "comingSoon.jpg", 
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        contact: "Pike",
        email: "email@gmail.com"
    },
    {
        id: 6,
        name: "Delts Angels", 
        image: "comingSoon.jpg", 
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        contact: "Delt",
        email: "email@gmail.com"
    },
    {
        id: 7,
        name: "Kappa Sigma Margaritaville", 
        image: "comingSoon.jpg", 
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        contact: "Kappa Sigma",
        email: "email@gmail.com"
    },
    {
        id: 8,
        name: "Beta Born in the USA", 
        image: "comingSoon.jpg", 
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        contact: "Beta",
        email: "email@gmail.com"
    },
    {
        id: 9,
        name: "Willystock",
        image: "comingSoon.jpg",
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        contact: "Centuries",
        email: "email@gmail.com"
    },
    {
        id: 10,
        name: "Chili Olympics",
        image: "comingSoon.jpg",
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        contact: "AMA",
        email: "email@gmail.com"
    },
    {
        id: 11,
        name: "Shipwrecked",
        image: "comingSoon.jpg",
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        contact: "Sig Ep",
        email: "email@gmail.com"
    },
    {
        id: 12,
        name: "Phis in Cairo",
        image: "comingSoon.jpg",
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        contact: "Alpha Sig/Delta Sig/Phi Psi",
        email: "email@gmail.com"
    },
    {
        id: 13,
        name: "The Donks",
        image: "comingSoon.jpg",
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        contact: "Ol' Ags",
        email: "email@gmail.com"
    },
    {
        id: 14,
        name: "Taulapalooza",
        image: "comingSoon.jpg",
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        contact: "ATO/TKE",
        email: "email@gmail.com"
    },
    {
        id: 15,
        name: "Space Rodeo",
        image: "comingSoon.jpg",
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        contact: "SAE",
        email: "email@gmail.com"
    }
]