export default [
    {
        id: 1,
        name: "ACEtoberfest", 
        image: "ace.png", 
        link: "https://fb.me/e/blSXy29Xp",
        guys: 140,
        girls: 85,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "ACE",
        contact: "email@gmail.com"
    },
    {
        id: 2,
        name: "Phi Delt Las Vegas", 
        image: "comingSoon.jpg", 
        link: "https://www.eventbrite.com/e/phi-delt-las-vegas-tickets-731622431387?utm_experiment=test_share_listing&aff=ebdsshios",
        guys: 225,
        girls: 70,
        included: "shirt, koozie, food, Friday transportation",
        tshirt: "shirtSoon.jpg",
        org: "Phi Delt",
        contact: "email@gmail.com"
    },
    {
        id: 3,
        name: "The Masters",
        image: "comingSoon.jpg", 
        link: "https://my.cheddarup.com/c/the-masters-at-chilifest?cart=13f83d53-836b-4fe0-a352-f63676656dd1%21%2169892328",
        guys: 170,
        girls: 70,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "Gents/Suits",
        contact: "email@gmail.com"
    },
    {
        id: 4,
        name: "Sigma Chi Yacht Club", 
        image: "comingSoon.jpg", 
        link: "https://www.cognitoforms.com/AggieSigmaChi1/SIGMACHIYACHTCLUB",
        guys: 200,
        girls: 85,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "Sigma Chi",
        contact: "email@gmail.com"
    },
    {
        id: 5,
        name: "Pike Saloon", 
        image: "comingSoon.jpg", 
        link: "https://www.facebook.com/events_invite_off_fb/link_sharing/1531239684328617/?inviter_id=100045511810989&token=DesImGqH4OK7Zdyhs8LanUTlnvvCAeOEkOdJJfnzeLE",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "Pike",
        contact: "email@gmail.com"
    },
    {
        id: 6,
        name: "Delts Angels", 
        image: "comingSoon.jpg", 
        link: "https://my.cheddarup.com/c/delts-angels?cart=06ce22e7-7c54-48f6-a204-44d95640d20f%21%2169891782",
        guys: 185,
        girls: 80,
        included: "shirt, fanny pack, bandana, tattoos, chapstick",
        tshirt: "shirtSoon.jpg",
        org: "Delt",
        contact: "email@gmail.com"
    },
    {
        id: 7,
        name: "Kappa Sigma Margaritaville", 
        image: "comingSoon.jpg", 
        link: "https://my.cheddarup.com/c/kappa-sigma-chilifest24?cart=b9ea2390-67a7-4016-9a3c-d8022f46ee73%21%2169892418",
        guys: 180,
        girls: 95,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "Kappa Sig",
        contact: "email@gmail.com"
    },
    {
        id: 8,
        name: "Beta Born in the USA", 
        image: "comingSoon.jpg", 
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "Beta",
        contact: "email@gmail.com"
    },
    {
        id: 9,
        name: "Willystock",
        image: "comingSoon.jpg",
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "Centuries",
        contact: "email@gmail.com"
    },
    {
        id: 10,
        name: "Chili Olympics",
        image: "comingSoon.jpg",
        link: "https://amaolympics.squarespace.com/",
        guys: 185,
        girls: 75,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "AMA",
        contact: "email@gmail.com"
    },
    {
        id: 11,
        name: "Shipwrecked",
        image: "comingSoon.jpg",
        link: "https://www.bouncelife.com/events/6571ef70a2e4796d97f9ecb1",
        guys: 160,
        girls: 69,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "Sig Ep",
        contact: "email@gmail.com"
    },
    {
        id: 12,
        name: "Phis in Cairo",
        image: "comingSoon.jpg",
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "Alpha Sig/Delta Sig/Phi Psi",
        contact: "email@gmail.com"
    },
    {
        id: 13,
        name: "The Donks",
        image: "comingSoon.jpg",
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "Ol' Ags",
        contact: "email@gmail.com"
    },
    {
        id: 14,
        name: "Taulapalooza",
        image: "comingSoon.jpg",
        link: "https://taulapalooza.store/",
        guys: 160,
        girls: 70,
        included: "Friday transportation, fanny pack, food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "ATO/TKE",
        contact: "email@gmail.com"
    },
    {
        id: 15,
        name: "Space Rodeo",
        image: "comingSoon.jpg",
        link: "https://www.tamusae.com/store/p30/Male_Guest_Wristband.html",
        guys: 210,
        girls: 75,
        included: "Friday transportation, food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "SAE",
        contact: "email@gmail.com"
    },
    {
        id: 16,
        name: "Fiji 500",
        image: "comingSoon.jpg",
        link: "fijichilifest.com",
        guys: 145,
        girls: 85,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "Fiji",
        contact: "email@gmail.com"
    },
    {
        id: 17,
        name: "Paradigm",
        image: "comingSoon.jpg",
        link: "https://fb.me/e/blSXy29Xp",
        guys: 999,
        girls: 999,
        included: "food, drinks, shirt",
        tshirt: "shirtSoon.jpg",
        org: "Paradigm",
        contact: "email@gmail.com"
    }
]